### ISSUE TITLE
Project-Website unreachable

### ISSUE THREAD

**Issue by TheOkeland** [Sync-my-L2P/Sync-my-L2P#112]
Tried to go to the Web page, but I receive a "Site not reachable"-Error.

**Comment by auxua** [comment]
The domain "sync-my-l2p.de" is not registered anymore. Since 13.10. it is in Redemption Grace Period.

**Comment by Sync-my-L2P** [comment]
Thanks for the notice. I will renew the registration period.

Von: auxua
Gesendet: Samstag, 14. Oktober 2017 23:38
An: Sync-my-L2P/Sync-my-L2P
Cc: Subscribed
Betreff: Re: [Sync-my-L2P/Sync-my-L2P] Project-Website unreachable (#112)

The domain "sync-my-l2p.de" is not registered anymore. Since 13.10. it is in Redemption Grace Period.

**Comment by Klorkson** [comment]
Since the domain still is not reachable, could you at least give us the numerical IP, so users, wanting do download the program and find this thread, still have access to the program?

**Comment by LingMan** [comment]
There are binaries available here on Github: https://github.com/Sync-my-L2P/Sync-my-L2P/releases

**Comment by Lenni** [comment]
The website is reachable again, under http://syncmyl2p.de
