### ISSUE TITLE
Errors at start again

### ISSUE THREAD

**Issue by claell** [Sync-my-L2P/Sync-my-L2P#90]
I got some error messages at start:
![f9fda77c-a7dc-11e5-8077-ab4218b4c222](https://cloud.githubusercontent.com/assets/6171135/11929982/d681193e-a7df-11e5-9c11-bb2513b02587.png)

**Comment by justin-time** [comment]
This looks like a new kind of error messages if a module is not used in a "Lernraum". 
Because of the bulk of this message, SmL2P is mostly unusable for me. I really dislike such kind of changes of the API.

**Comment by Sync-my-L2P** [comment]
If a course e.g. doesn't use Media Libraries, the server responded with empty data up to now. Now an error is responded. I already fixed this problem and will upload the solution after cleaning the code.

**Comment by claell** [comment]
Thanks

**Comment by auxua** [comment]
Hi, just a quick comment on this about the api:

Already in the past, this error was returned if a module *is* deactivated and never *was*. (Managers of course rooms can deactivate features later on.)

The new thing about this since wednesday is:
If a feature *is* deactivated, but *was* before, the API now also responses with this error. 

We announced this change/Fix before deployment and it was critical, because in this case in the past, via the API documents had been visible, which the managers did not want to be visible.
